# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import protos.questions_pb2 as questions__pb2


class QuestionAnswerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAnswer = channel.unary_unary(
                '/questionAnswer.QuestionAnswer/GetAnswer',
                request_serializer=questions__pb2.QuestionRequest.SerializeToString,
                response_deserializer=questions__pb2.AnswerResponse.FromString,
                )


class QuestionAnswerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAnswer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QuestionAnswerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAnswer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAnswer,
                    request_deserializer=questions__pb2.QuestionRequest.FromString,
                    response_serializer=questions__pb2.AnswerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'questionAnswer.QuestionAnswer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class QuestionAnswer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAnswer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/questionAnswer.QuestionAnswer/GetAnswer',
            questions__pb2.QuestionRequest.SerializeToString,
            questions__pb2.AnswerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
